export interface Area {
  name: string;
}

export interface City {
  name: string;
  areas: Area[];
}

export const CITIES: City[] = [
  {
    name: "Karachi",
    areas: [
      { name: "Clifton" },
      { name: "DHA" },
      { name: "Gulshan-e-Iqbal" },
      { name: "Gulistan-e-Jauhar" },
      { name: "Korangi" },
      { name: "Landhi" },
      { name: "Malir" },
      { name: "Nazimabad" },
      { name: "North Karachi" },
      { name: "PECHS" },
      { name: "Saddar" },
      { name: "Shah Faisal" },
      { name: "Scheme 33" },
      { name: "Tariq Road" },
      { name: "University Road" },
    ],
  },
  {
    name: "Lahore",
    areas: [
      { name: "Cantt" },
      { name: "DHA" },
      { name: "Gulberg" },
      { name: "Gulshan-e-Ravi" },
      { name: "Ichhra" },
      { name: "Johar Town" },
      { name: "Model Town" },
      { name: "Muslim Town" },
      { name: "Shadman" },
      { name: "Township" },
      { name: "Valencia" },
      { name: "Wapda Town" },
    ],
  },
  {
    name: "Islamabad",
    areas: [
      { name: "F-6" },
      { name: "F-7" },
      { name: "F-8" },
      { name: "F-10" },
      { name: "F-11" },
      { name: "G-6" },
      { name: "G-7" },
      { name: "G-8" },
      { name: "G-9" },
      { name: "G-10" },
      { name: "G-11" },
      { name: "E-7" },
      { name: "I-8" },
      { name: "I-9" },
      { name: "I-10" },
    ],
  },
  {
    name: "Rawalpindi",
    areas: [
      { name: "Adiala Road" },
      { name: "Airport Housing" },
      { name: "Chaklala" },
      { name: "Committee Chowk" },
      { name: "Dhoke Khabba" },
      { name: "Gulshan Dadan Khan" },
      { name: "Lalkurti" },
      { name: "Pirwadhai" },
      { name: "Ratta Amral" },
      { name: "Saddar" },
      { name: "Satellite Town" },
      { name: "Westridge" },
    ],
  },
  {
    name: "Faisalabad",
    areas: [
      { name: "Aminpur Bazar" },
      { name: "Batala Colony" },
      { name: "Chenab Colony" },
      { name: "Civil Lines" },
      { name: "D Ground" },
      { name: "Ghulam Muhammadabad" },
      { name: "Gulberg" },
      { name: "Jaranwala Road" },
      { name: "Jinnah Colony" },
      { name: "Madina Town" },
      { name: "Peoples Colony" },
      { name: "Samanabad" },
      { name: "Satayana Road" },
    ],
  },
  {
    name: "Multan",
    areas: [
      { name: "Basti Maluk" },
      { name: "Chungi No. 9" },
      { name: "Gulgasht" },
      { name: "Hussain Agahi" },
      { name: "Jinnah Town" },
      { name: "Khanewal Road" },
      { name: "New Multan" },
      { name: "Shah Rukn-e-Alam" },
      { name: "Sher Shah Road" },
      { name: "Wapda Town" },
    ],
  },
  {
    name: "Peshawar",
    areas: [
      { name: "Cantt" },
      { name: "Dalazak Road" },
      { name: "Faqirabad" },
      { name: "Gulbahar" },
      { name: "Hayatabad" },
      { name: "Kohat Road" },
      { name: "Nowshera Road" },
      { name: "Ring Road" },
      { name: "Saddar" },
      { name: "University Town" },
    ],
  },
  {
    name: "Hyderabad",
    areas: [
      { name: "Cantt" },
      { name: "City Market" },
      { name: "Gari Khata" },
      { name: "Hirabad" },
      { name: "Latifabad" },
      { name: "Market Tower" },
      { name: "Qasimabad" },
      { name: "Saddar" },
      { name: "Site Area" },
    ],
  },
  {
    name: "Quetta",
    areas: [
      { name: "Cantt" },
      { name: "Chiltan Town" },
      { name: "Jinnah Town" },
      { name: "M.A. Jinnah Road" },
      { name: "Nawa Killi" },
      { name: "Samungli Road" },
      { name: "Sariab Road" },
      { name: "Zarghoon Road" },
    ],
  },
  {
    name: "Sialkot",
    areas: [
      { name: "Cantt" },
      { name: "Daska Road" },
      { name: "Gulshan-e-Iqbal" },
      { name: "Iqbal Town" },
      { name: "Kashmir Road" },
      { name: "Khayaban" },
      { name: "Marala Road" },
      { name: "Paris Road" },
    ],
  },
  {
    name: "Gujranwala",
    areas: [
      { name: "Cantt" },
      { name: "Civil Lines" },
      { name: "G.T. Road" },
      { name: "Jinnah Road" },
      { name: "Model Town" },
      { name: "Nizamabad" },
      { name: "Saddar" },
      { name: "Satellite Town" },
    ],
  },
  {
    name: "Other",
    areas: [{ name: "Other" }],
  },
];
